bobo-diallo/inserjeune

- .gitignore
- assets/js/app.js
- assets/styles/app.css
- assets/styles/pinsuprem.scss
- assets/styles/style.scss
- composer.json
- phpunit.xml.dist
- src/Controller/CompanyController.php
- src/Controller/PersonDegreeController.php
- src/Controller/SchoolController.php
- src/DataFixtures/AppFixtures.php
- src/Twig/DashboardExtension.php
- templates/Dashboard/index.html.twig
- templates/_footer.html.twig
- templates/_menu_sidebar_left.html.twig
- templates/company/index.html.twig
- templates/persondegree/index.html.twig
- templates/school/index.html.twig
- tests/bootstrap.php
> IFEF-Denis-01: Design export datatable. Ajout delete option dans les Index. Correction Bug Dashboard diplômé par secteurs

- assets/styles/style.scss
- migrations/Version20221015074942.php
- src/Controller/Front/FrontSchoolController.php
- src/Entity/Company.php
- src/Entity/PersonDegree.php
- src/Repository/CityRepository.php
- src/Twig/EnrollementExention.php
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-Denis-02: Enrollement personnDegrees et Companies

- templates/school/companiesEnroll.html.twig
> IFEF-Denis-03: JobOffer CkEditor, design sur bouton import export enrolls

- assets/styles/style.scss
- src/Controller/PurgeController.php
- src/Repository/JobOfferRepository.php
- templates/purge/purge.html.twig
> IFEF-Denis-05: Purge Offers: menu, contrôleur, vue, repos

- assets/styles/style.scss
- src/Controller/GeoLocationController.php
> IFEF-Denis-06: FixBug Geolocalisation et ajout CSS InfoMaps

- src/Controller/Front/FrontSchoolController.php
- templates/school/companiesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-030: Import csv for compagnies enrollement

- src/Controller/SecurityController.php
> IFEF-031: Fix change locale

- templates/company/index.html.twig
…"app.request.attributes.get('_route')"
> IFEF-Denis-07: FixBug lang Vos Partenaire "app.request.pathinfo" par "app.request.attributes.get('_route')"

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-Denis-09: Enroll save_all

- config/services.yaml
- src/Controller/DashboardController.php
- src/Controller/Front/FrontCompanyController.php
- src/Controller/Front/FrontCompanyJobOfferController.php
- src/Controller/Front/FrontPersonDegreeController.php
- src/Controller/Front/FrontPersonDegreeSatisfactionController.php
- src/Controller/Front/FrontSchoolController.php
- src/Controller/PurgeController.php
- src/Entity/Role.php
- src/Event/RoutingSubscriber.php
- src/Form/PersonDegreeType.php
- src/Repository/UserRepository.php
- src/Services/CompanyService.php
- src/Services/DashboardService.php
- src/Services/PersonDegreeService.php
- src/Services/SchoolService.php
- templates/base_degree.html.twig
- templates/persondegree/content.html.twig
> IFEF-033: Fix lenteur de l'interface diplome et redirection multiple à la connexion

- migrations/Version20221024100548.php
- migrations/Version20221024105940.php
- migrations/Version20221024113911.php
- src/Controller/Front/FrontSchoolController.php
- src/Entity/Company.php
- src/Entity/School.php
- src/Validatior/Constraints/DuplicateSchoolRegistered.php
- src/Validatior/Constraints/DuplicateSchoolRegisteredValidator.php
> IFEF-034: Mettre Matricule etablissement à unique

- README.md
- composer.json
- config/bundles.php
- config/packages/fm_elfinder.yaml
- config/packages/fos_ckeditor.yaml
- config/packages/messenger.yaml
- config/routes/fm_elfinder.yaml
- config/services.yaml
- migrations/Version20221024224624.php
- migrations/Version20221025095755.php
- migrations/Version20221026093641.php
- migrations/Version20221026111006.php
- src/Controller/Front/FrontCompanyJobOfferController.php
- src/Controller/Front/FrontPersonDegreeController.php
- src/Controller/JobOfferController.php
- src/Entity/Candidate.php
- src/Entity/JobOffer.php
- src/Form/CandidateType.php
- src/Form/JobOfferType.php
- src/Repository/JobOfferRepository.php
- src/Services/CompanyService.php
- src/Services/EmailService.php
- src/Services/FileUploader.php
- templates/frontCompanyJobOffer/_new.html.twig
- templates/frontCompanyJobOffer/content.html.twig
- templates/frontCompanyJobOffer/index.html.twig
- templates/frontCompanyJobOffer/show.html.twig
- templates/frontPersondegree/candidate.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-035: Gestion des offre d'emploi (candidature, offre vue, ajout et candidature avec fichier joint)

- .gitignore
- composer.lock
> IFEF-035: Add composer.lock

- README.md
- src/Services/DashboardService.php
> IFEF-036: Not restrict dashboard for school and company

- README.md
- config/packages/messenger.yaml
- src/Controller/Front/FrontSchoolController.php
- src/Services/EmailService.php
- templates/base_school.html.twig
- templates/email/enrollement_persondegree.html.twig
> IFEF-037: Send email notification of enlisted person degree

- config/packages/messenger.yaml
- migrations/Version20221027111314.php
- migrations/Version20221027112605.php
- migrations/Version20221027113741.php
- migrations/Version20221027114125.php
- migrations/Version20221027114427.php
- src/Controller/Front/FrontPersonDegreeSatisfactionController.php
- src/Entity/Person.php
- src/Validatior/Constraints/UniqueEmail.php
- src/Validatior/Constraints/UniqueEmailValidator.php
- templates/country/_new.html.twig
- templates/country/index.html.twig
- templates/country/show.html.twig
- templates/currency/content.html.twig
- templates/satisfactioncreator/_new.html.twig
- templates/satisfactioncreator/show.html.twig
- templates/satisfactionsalary/_new.html.twig
- templates/satisfactionsalary/show.html.twig
> IFEF-038: Prepare deployment on OIF server

- assets/styles/style.scss
- src/Controller/Front/FrontCompanyController.php
- templates/_menu_sidebar_left.html.twig
- templates/base_company.html.twig
- templates/company/_new.html.twig
- templates/frontCompanyJobOffer/_new.html.twig
- templates/frontCompanyJobOffer/show.html.twig
- templates/persondegree/_new.html.twig
- templates/school/_new.html.twig
> IFEF-Denis-11: Menus and preparations for documentation

- assets/styles/style.scss
- src/Twig/EnrollementExention.php
- templates/_apropos.html.twig
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
…d save_all button, add delete_selection button and add send_mail_selection button
Following points must be confirmed and checked explicitly by code …
> IFEF-Denis-12: enrollment: change remove button by checkBox input, add save_all button, add delete_selection button and add send_mail_selection button

- templates/school/index.html.twig
> IFEF-Denis-13: company: can see theirs schools partners, suppress Archiver button in all views

- src/Controller/GeoLocationController.php
- templates/company/content.html.twig
- templates/persondegree/content.html.twig
- templates/school/content.html.twig
…Degree: add TYPE_SEARCH on request
> IFEF-Denis-17: Localisation manual/auto clean code and FixBugg personDegree: add TYPE_SEARCH on request

- assets/js/app.js
- public/downloads/company_enrollment_template.csv
- public/downloads/person_degree_enrollment_template.csv
- src/Controller/Front/FrontCompanyJobOfferController.php
- src/Controller/Front/FrontSchoolJobOfferController.php
- src/Repository/JobOfferRepository.php
- src/Twig/CheckDatabaseExention.php
- src/Twig/EnrollementExention.php
- templates/_footer.html.twig
- templates/content.html.twig
- templates/country/_new.html.twig
- templates/frontCompanyJobOffer/_new.html.twig
- templates/frontCompanyJobOffer/show.html.twig
- templates/frontSchoolJobOffer/_new.html.twig
- templates/jobOffer/_new.html.twig
- templates/persondegree/index.html.twig
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-041: Fix bugs of QA recettage-migration-v1-oct22

- migrations/Version20221110123752.php
> IFEF-041: Prepare database for deployment

- config/routes.yaml
- migrations/Version20221111111706.php
- migrations/Version20221111111844.php
- src/Controller/HomeController.php
- src/Controller/SecurityController.php
- templates/_apropos.html.twig
> IFEF-042: Fix redirection of home page

- README.md
- templates/email/enrollement_company.html.twig
- templates/email/enrollement_persondegree.html.twig
- templates/email/reset_password.html.twig
> IFEF-045: Use sendmail for inserjeune server

- migrations/Version20221125085906.php
- migrations/Version20221125090507.php
- src/Entity/Activity.php
- src/Entity/Contract.php
- src/Entity/Degree.php
- src/Entity/InfoCreator.php
- src/Entity/JobOffer.php
- src/Entity/LegalStatus.php
- src/Entity/Profession.php
- src/Entity/School.php
- src/Entity/SectorArea.php
- templates/satisfactioncompany/_new.html.twig
> IFEF-046: Change entity description type, from STRING to TEXT

- src/Controller/Security/RegisterController.php
- src/Entity/Person.php
- src/Entity/User.php
- src/Form/PersonDegreeType.php
- templates/persondegree/_new.html.twig
- templates/user/register.html.twig
> IFEF-047: Show error message of registration

- assets/js/app.js
- templates/persondegree/_new.html.twig
- templates/persondegree/content.html.twig
…en registration is valid, student can't change it
> IFEF-Denis-18: FixBug on validation regitration student by school, when registration is valid, student can't change it

- config/services.yaml
- migrations/Version20230109095050.php
- src/Controller/DefaultController.php
- src/Entity/AvatarDTO.php
- src/Entity/JobOffer.php
- src/Entity/Person.php
- src/Entity/User.php
- src/Form/AvatarType.php
- src/Model/PersonDegreeReadOnly.php
- src/Services/FileUploader.php
- src/Validatior/Constraints/DuplicateSchoolRegisteredValidator.php
- templates/Dashboard/index.html.twig
- templates/_footer.html.twig
- templates/_image_profile.html.twig
- templates/base.html.twig
- templates/base_company.html.twig
- templates/base_degree.html.twig
- templates/base_legislator.html.twig
- templates/base_school.html.twig
- templates/frontCompanyJobOffer/_new.html.twig
- templates/frontCompanyJobOffer/index.html.twig
- templates/frontCompanyJobOffer/show.html.twig
- templates/frontSchoolJobOffer/index.html.twig
- templates/jobOffer/index.html.twig
- templates/school/_new.html.twig
- templates/school/show.html.twig
- templates/user/avatar.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-050: Ajout image profil 

- config/packages/fos_ckeditor.yaml
- templates/frontPersondegree/candidate.html.twig
- templates/school/index.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-051: Suppression d'ajout d'image à partir de cheditor

- src/Controller/PersonDegreeController.php
- src/Repository/PersonDegreeRepository.php
- src/Repository/SatisfactionCreatorRepository.php
- src/Repository/SatisfactionSalaryRepository.php
- src/Repository/SatisfactionSearchRepository.php
- src/Twig/CheckDatabaseExention.php
- templates/persondegree/index.html.twig
- webpack.config.js
> IFEF-052: Performance affichage person degree (admin interface)

- src/Controller/Security/UserController.php
- src/Entity/Person.php
- src/Model/UserReadOnly.php
- src/Repository/PersonDegreeRepository.php
- src/Repository/UserRepository.php
- templates/base.html.twig
- templates/persondegree/index.html.twig
- templates/user/index.html.twig
> IFEF-053: Performance affichage users (admin interface)

- migrations/Version20230120163040.php
- migrations/Version20230121103729.php
- migrations/Version20230121103814.php
- migrations/Version20230121105241.php
- src/Controller/Front/FrontPersonDegreeController.php
- src/Entity/JobOffer.php
- templates/jobOffer/index.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-Denis-20: affiche si la candidature a déjà été envoyée

- assets/js/app.js
- assets/styles/style.scss
- src/Controller/Front/FrontSchoolController.php
- src/Repository/SchoolRepository.php
- src/Twig/DashboardExtension.php
- templates/Dashboard/index.html.twig
- templates/GeoLocation/maps.html.twig
- templates/company/content.html.twig
- templates/persondegree/content.html.twig
- templates/school/content.html.twig
> IFEF-Denis-21: Dashboard et Geolocation

- assets/styles/style.scss
- src/Controller/Front/FrontCompanyController.php
- src/Controller/Front/FrontPersonDegreeController.php
- src/Controller/Front/FrontSchoolController.php
- src/Controller/PurgeController.php
- src/Repository/CompanyRepository.php
- src/Repository/PersonDegreeRepository.php
- src/Repository/SchoolRepository.php
- templates/company/content.html.twig
- templates/persondegree/content.html.twig
- templates/persondegree/index.html.twig
- templates/purge/purge.html.twig
- templates/school/content.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
… add function in school for editing students: email and phone
> IFEF-Denis-22: Geolocation fixBug missing and duplicated coordinates, add function in school for editing students: email and phone

- assets/js/app.js
- config/services.yaml
- src/Controller/Front/FrontSchoolController.php
- src/Controller/SessionTimeoutController.php
- src/Entity/JobOffer.php
- src/Event/Listener/SessionTimeoutListener.php
- src/Event/SessionTimeoutEvent.php
- src/Form/JobOfferType.php
- src/Form/SchoolType.php
- templates/_footer.html.twig
- templates/_footer_customize.html.twig
- templates/activity/index.html.twig
- templates/base_school.html.twig
- templates/city/index.html.twig
- templates/contract/index.html.twig
- templates/country/index.html.twig
- templates/currency/index.html.twig
- templates/degree/index.html.twig
- templates/frontSchoolJobOffer/_new.html.twig
- templates/frontSchoolJobOffer/edit.html.twig
- templates/frontSchoolJobOffer/new.html.twig
- templates/legalstatus/index.html.twig
- templates/region/index.html.twig
- templates/role/index.html.twig
- templates/sectorarea/index.html.twig
> Ifef 055: Augmentation taille tableau exportés sur PDF -  Logout user if inactive at 30 mn

- src/Controller/PurgeController.php
> IFEF-Denis-24: Fix Bugg on Clean Loacalizations on PersonDegree

- assets/styles/style.scss
- src/Controller/Front/FrontPersonDegreeController.php
- src/Controller/Security/RegisterController.php
- src/Entity/Person.php
- src/Entity/User.php
- src/Form/UserType.php
- templates/persondegree/_new.html.twig
- templates/persondegree/content.html.twig
- templates/user/register.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-Denis-25: Create option for creating new account for student resident in other country

- migrations/Version20230127162144.php
- migrations/Version20230127163944.php
> IFEF-Denis-27 : add migration

- src/Controller/Front/FrontSchoolController.php
- src/Twig/DashboardExtension.php
…llment and fixbugg to see le last enrolled persondegree on dashboard
> IFEF-Denis-28 : FixBugg persondegree and company connexion after enrollment and fixbugg to see le last enrolled persondegree on dashboard

- src/Controller/Front/FrontPersonDegreeSatisfactionController.php
- src/Controller/Front/FrontSchoolController.php
- src/Form/AvatarType.php
- src/Twig/DashboardExtension.php
- templates/jobOffer/content.html.twig
- templates/jobOffer/index.html.twig
- templates/jobOffer/show.html.twig
- templates/school/content.html.twig
- templates/user/avatar.html.twig
> Ifef denis 29: fixbugg from Rosalie Recettage file with (DP) annotations

- assets/js/app.js
- src/Services/CompanyService.php
- templates/Dashboard/index.html.twig
- templates/_footer.html.twig
- templates/company/index.html.twig
- templates/jobOffer/index.html.twig
- templates/persondegree/index.html.twig
- templates/user/avatar.html.twig
> IFEF-056: Fix bug

- src/Validatior/Constraints/UniqueEmailValidator.php
> IFEF-057: Not add the current user's email when checking existing email

- public/locale/fr_FR.json
- src/Entity/JobOffer.php
- src/Form/UserType.php
- templates/_footer.html.twig
- templates/company/index.html.twig
- templates/frontSchoolJobOffer/show.html.twig
- templates/jobOffer/index.html.twig
- templates/jobOffer/show.html.twig
> IFEF-058: Show link of job's description in details job.

- src/Controller/Front/FrontPersonDegreeController.php
- templates/base_degree.html.twig
> IFEF-Denis-30 : FixBuggs create account without diaspora

- src/Form/UserType.php
- templates/satisfactionSearch/show.html.twig
- templates/user/register.html.twig
> IFEF-059: Fix bug on registration form

- src/Controller/Front/FrontPersonDegreeController.php
- templates/jobOffer/index.html.twig
- templates/satisfactionSearch/show.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> IFEF-060: Fix recettage-migration-v2-fev23

- templates/base_company.html.twig
- templates/base_degree.html.twig
- templates/base_school.html.twig
- templates/company/content.html.twig
- templates/persondegree/content.html.twig
- templates/persondegree/index.html.twig
- templates/school/content.html.twig
…rofile, suppress second collumn of Establisment in persondegrees index
> IFEF-Denis-32 : FixBugg alert on change phoneNumber in PersonDegree profile, suppress second collumn of Establisment in persondegrees index

- src/Command/CleanDatabaseForCountryCommand.php
- src/Command/CreateAdminUserCommand.php
- src/Command/ListCountriesCommand.php
- src/Command/RemoveUserCommand.php
- src/Entity/City.php
- src/Entity/JobOffer.php
- src/Entity/Region.php
- src/Entity/User.php
> IFEF-061: Create command to prepare country migration

- templates/purge/purge.html.twig
> IFEF-Denis-33 : Rewrite comments in purge.html.twig to fix bad syntax

- src/Controller/PurgeController.php
- templates/purge/purge.html.twig
> IFEF-Denis-34 : FixBuggs purge

- migrations/Version20230227130251.php
- src/Command/CleanDatabaseForCountryCommand.php
- src/Command/RemoveUserCommand.php
> IFEF-064: Remove on cascade user_role when deleting user or role

- src/Controller/GeoLocationController.php
- src/Controller/PurgeController.php
- src/Repository/CompanyRepository.php
- src/Repository/PersonDegreeRepository.php
- src/Repository/SchoolRepository.php
- templates/purge/purge.html.twig
…, FixBug clean same coordinate time too long
> IFEF-Denis-35 : FixBug geolocalisation for PersonDegrees without city, FixBug clean same coordinates time too long

- templates/persondegree/content.html.twig
> IFEF-Denis-37 : Set automatic calculate coordinates when account is in new mode

- src/Controller/Front/FrontSchoolController.php
…ername and canonical username in user
> IFEF-Denis-38: FixBug "Vos Diplomés" when change number phone, set username and canonical username in user

- src/Controller/Front/FrontCompanyController.php
- src/Controller/Front/FrontPersonDegreeController.php
- src/Controller/Front/FrontSchoolController.php
- src/Entity/User.php
> IFEF-067: Remove ON DELETE CASCADE (role) on $user->profils

- migrations/Version20230302154818.php
- src/Model/PersonDegreeReadOnly.php
- src/Repository/PersonDegreeRepository.php
> IFEF-068: Fix PersonDegreeRepository::getAllPersonDegree to select all personDegree

- README.md
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-069: Comment Import CSV button on enrolment menu

- templates/school/personDegreesEnroll.html.twig
> IFEF-Denis-41 : FixBug import csv enroll person degree to only import a part of data

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-Denis-42 : FixBug import csv enroll company to only import a part of data

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-070: Affichage d'un seul alert lorsque l'enrolment diplome a des problèmes

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-071: Affichage d'un seul alert lorsque l'enrolment diplome a des problemes

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-073: Fix error for validation import enrolment

- templates/user/register.html.twig
> IFEF-Denis-43 : change position on userType in registration vue

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
…nrollement person degree and company
> IFEF-Denis-44 : change message when creating/modifying new input in enrollement person degree and company

- assets/js/app.js
- src/Command/CleanDatabaseForCountryCommand.php
- src/Controller/Front/FrontPersonDegreeController.php
- src/Controller/SchoolController.php
- src/Services/ActivityService.php
- src/Services/EmailService.php
- src/Services/FileUploader.php
- src/Validatior/Constraints/DuplicateSchoolRegisteredValidator.php
- templates/Dashboard/index.html.twig
- templates/_footer.html.twig
- templates/_footer_customize.html.twig
- templates/base.html.twig
- templates/base_company.html.twig
- templates/base_degree.html.twig
- templates/base_legislator.html.twig
- templates/base_school.html.twig
- templates/satisfactioncompany/show.html.twig
- templates/user/register.html.twig
> IFEF-074: Fix bug of recettage-migration-v2-13mars23

- public/downloads/company_enrollment_template.csv
- public/downloads/person_degree_enrollment_template.csv
- templates/_footer_customize.html.twig
- templates/_head.html.twig
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-075: Fix title in enrolement template

- config/packages/security.yaml
- src/Controller/Front/FrontSchoolController.php
- src/Controller/Security/RegisterController.php
- templates/_apropos.html.twig
- templates/base_security.html.twig
- templates/information_rgpd.html.twig
- translations/security.fr.xlf
> IFEF-076: Fix recettage-migration-v2-06avril23

- assets/styles/style.scss
- migrations/Version20230411161345.php
- package-lock.json
- package.json
- src/Controller/Front/FrontPersonDegreeController.php
- src/Controller/PersonDegreeController.php
- src/Entity/PersonDegree.php
- src/Form/PersonDegreeType.php
- src/Repository/CountryRepository.php
- templates/persondegree/_new.html.twig
- templates/persondegree/content.html.twig
- templates/persondegree/show.html.twig
- templates/user/register.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
- webpack.config.js
…egree Profile and allow all countries in residence country for creating Account
Following points must be confirmed and checked explicitly by code …
> Denis IFEF-Denis-45 : Add Diaspora configuration function in Person Degree Profile and allow all countries in residence country for creating Account

- templates/Dashboard/index.html.twig
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
- translations/security.fr.xlf
…eate message for company and personDegree enroll
> Denis IFEF-Denis-47 : create new message when security disconnect, create message for company and personDegree enroll unique data

- migrations/Version20230419004905.php
- src/Command/CleanDatabaseForCountryCommand.php
- src/Command/CreateAdminUserCommand.php
- src/Entity/City.php
- webpack.config.js
> IFEF-077: Save all currencies, countries, regions and cities when clean database for a country

- templates/_head.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
… and meta keywords in _head.html.twig
> Denis IFEF-Denis-49 : SEO modify meta description and add meta robots and meta keywords in _head.html.twig

- templates/login/index.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> Denis IFEF-Denis-50 : SEO add <h1> in login vue

- templates/base_security.html.twig
- templates/login/index.html.twig
> Denis IFEF-Denis-51 : SEO fix bug IFEF-Denis-20 on login vue

- templates/Dashboard/index.html.twig
- templates/GeoLocation/maps.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
> Denis IFEF-Denis-52 : SEO add h1 geolocation and statistics

- src/Command/CleanDatabaseForCountryCommand.php
> IFEF-078: Clean database - make valid for the unique country

- config/services.yaml
- templates/_menu_sidebar_left.html.twig
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-080: Add portugais translation

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-Denis-53: fix bugg company_enroll and personDegreeEnroll on fields names with accents

- templates/activity/new.html.twig
> IFEF-Denis-54: modify title in add a new activity vue when administrator account

- assets/js/app.js
- src/Command/ImportTranslationFileFromCSVCommand.php
- src/Form/PersonDegreeType.php
- src/Services/CityService.php
- templates/persondegree/content.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-57 : improve all translations in personDegree profile

- assets/js/app.js
- src/Controller/Front/FrontSchoolController.php
- src/Controller/PurgeController.php
- templates/company/content.html.twig
- templates/persondegree/index.html.twig
- templates/purge/purge.html.twig
- templates/school/companiesEnroll.html.twig
- templates/school/content.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-59 : improve all translations in JS files on alert() and confirm() command

- src/Twig/DashboardExtension.php
- templates/Dashboard/index.html.twig
- templates/company/content.html.twig
- templates/persondegree/content.html.twig
- templates/school/content.html.twig
- translations/messages.en.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-60 : improve all translations in JS files on text()  command

- src/Controller/DefaultController.php
- src/Twig/DashboardExtension.php
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- webpack.config.js
> IFEF-082: Handle translation in twig extension

- src/Twig/DashboardExtension.php
- templates/Dashboard/index.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-62 : improve all translations in dashboard

- src/Form/UserType.php
- templates/login/index.html.twig
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
- templates/user/register.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-63 : improve all translations in register and fix bug in persondegreeEnroll

- src/Form/GeoLocationType.php
- templates/GeoLocation/maps.html.twig
> IFEF-Denis-65 : improve all translations Geolocation

- README.md
- src/Form/SatisfactionSalaryType.php
- templates/persondegree/content.html.twig
> IFEF-083: Handle translation in SatisfactionSalaryType

- src/Form/SatisfactionCompanyType.php
> IFEF-084: Handle translation in Satisfaction creator

- src/Form/SatisfactionCompanyType.php
- src/Form/SatisfactionSalaryType.php
- templates/satisfactioncompany/_new.html.twig
- templates/satisfactioncompany/content.html.twig
- templates/satisfactionsalary/content.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-085: Handle translation in Satisfaction company

- src/Form/UserType.php
> IFEF-Denis-66 : translation for menu user type in create account vue

- assets/js/app.js
- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-66 : translation for menu user type in create account vues

- translations/messages.en.xlf
> IFEF-Denis-67 : Update en translations

- templates/school/companiesEnroll.html.twig
- templates/school/personDegreesEnroll.html.twig
> IFEF-Denis-69 : improve translations in enrollment placeholders

- templates/school/personDegreesEnroll.html.twig
> IFEF-Denis-70 : Add translation button Add graduate in enrollment personDegree

- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-71 : update translation files

- templates/country/edit.html.twig
- templates/country/index.html.twig
- templates/purge/purge.html.twig
- templates/sectorarea/edit.html.twig
- templates/sectorarea/index.html.twig
- templates/sectorarea/new.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-73 : improve translations for administration tables

- assets/js/app.js
- src/Controller/DefaultController.php
- src/Controller/Front/FrontSchoolController.php
- src/Services/PersonDegreeService.php
- templates/base.html.twig
- templates/base_company.html.twig
- templates/base_degree.html.twig
- templates/base_legislator.html.twig
- templates/base_school.html.twig
- templates/company/_new.html.twig
- templates/company/index.html.twig
- templates/frontCompanyJobOffer/content.html.twig
- templates/information_rgpd_en.html.twig
- templates/satisfactioncompany/show.html.twig
- templates/school/_new.html.twig
- templates/school/content.html.twig
- templates/school/show.html.twig
- templates/user/_new.html.twig
- templates/user/edit.html.twig
- templates/user/index.html.twig
- templates/user/new.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-74 : Updates of Rosalie recipe on 2023 july 5

- templates/school/_new.html.twig
- templates/school/show.html.twig
- translations/messages.en.xlf
> IFEF-Denis-75 : Updates of Rosalie recipe on 2023 july 12

- src/Controller/PersonDegreeController.php
- templates/frontSchoolJobOffer/content.html.twig
- templates/jobOffer/content.html.twig
- templates/persondegree/index.html.twig
- templates/persondegree/show.html.twig
> IFEF-Denis-78: fixbug for create tvet job offer and improve translations

- assets/js/app.js
- assets/styles/style.scss
- src/Controller/Front/FrontSchoolController.php
- src/Twig/EnrollementExention.php
- templates/Dashboard/index.html.twig
- templates/frontPersondegree/candidate.html.twig
- templates/satisfactionSearch/content.html.twig
- templates/satisfactioncompany/content.html.twig
- templates/satisfactioncompany/show.html.twig
- templates/satisfactioncreator/content.html.twig
- templates/school/_new.html.twig
- templates/school/content.html.twig
- templates/school/index.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-Denis-79: fixbug recettage-rwada Rosalie 2023/07/24

- migrations/Version20231120235230.php
- src/Entity/Person.php
- src/Form/PersonDegreeType.php
- templates/jobOffer/index.html.twig
- templates/persondegree/show.html.twig
> IFEF-V342_03: Fix birthday date format

- assets/js/app.js
- src/Entity/PersonDegree.php
- src/Form/PersonDegreeType.php
> IFEF-V342_04: Restriction of birth day date

- src/Controller/Front/FrontSchoolController.php
- src/Twig/EnrollementExention.php
- templates/school/personDegreesEnroll.html.twig
> IFEF-V342_05: Fix birthday date in personDegreesEnrollement

- src/Command/SendMailRelaunchCommand.php
- src/Services/EmailService.php
- templates/email/relaunch_company.html.twig
- templates/email/relaunch_graduate.html.twig
- templates/frontPersondegree/satisfactions.html.twig
- templates/persondegree/show.html.twig
- templates/satisfactioncreator/index.html.twig
- templates/satisfactioncreator/show.html.twig
- templates/school/companiesEnroll.html.twig
…bug on satisfactioncreator survey
> INSERJEUNE-V342_06: FixBug after Rosalie Recipe on 2024/01/16 except bug on satisfactioncreator survey

- migrations/Version20240119112828.php
- src/Entity/SatisfactionSearch.php
> IFEF-V342_06: Make job_time nullable in SatisfactionSearch entity

- templates/satisfactionSearch/show.html.twig
> INSERJEUNE-V342_10: translate "diploma sought" in satisfactionSearch/show

- src/Entity/SatisfactionSalary.php
- src/Form/SatisfactionSalaryType.php
- templates/satisfactionsalary/content.html.twig
> IFEF-V342_07: Add other post in SatisfactionSalary::jobStatus options

- templates/persondegree/show.html.twig
> IFEF_V342-09: Hide Add new persondegree button on vue detail

- README.md
- src/Controller/DefaultController.php
- src/Controller/Front/FrontPersonDegreeSatisfactionController.php
- src/Controller/Front/FrontSchoolController.php
- src/Controller/JobOfferController.php
- src/Controller/PersonDegreeController.php
- templates/company/index.html.twig
- templates/jobOffer/_new.html.twig
- templates/jobOffer/content.html.twig
- templates/persondegree/index.html.twig
- templates/school/employers.html.twig
- templates/school/personDegreesEnroll.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-V342_11: Enrolment student:  fix undefined option is activity list

- config/services.yaml
> IFEF-V342_12: Export mail_from et mail_to to .env

- src/Controller/Front/FrontSchoolController.php
- src/Controller/JobOfferController.php
- src/Form/JobOfferType.php
- src/Services/EmailService.php
- templates/email/enrollement_persondegree.html.twig
- templates/frontPersondegree/candidate.html.twig
- templates/jobOffer/index.html.twig
- templates/persondegree/show.html.twig
> IFEF-V342_13: Show error when upload file in job offer exceded 2M

- src/Controller/Front/FrontSchoolController.php
- src/Entity/Person.php
- src/Form/CandidateType.php
- templates/frontPersondegree/candidate.html.twig
- translations/messages.fr.xlf
> IFEF-V342_14: Fix error birthday date

- composer.json
- config/bundles.php
- config/packages/knp_paginator.yaml
- config/services.yaml
- src/Controller/Front/FrontSchoolController.php
- src/Controller/PersonDegreeController.php
- src/Controller/Security/UserController.php
- src/Repository/PersonDegreeRepository.php
- templates/_footer.html.twig
- templates/_pagination.html.twig
- templates/persondegree/index.html.twig
- templates/user/index.html.twig
- webpack.config.js
> IFEF-V342_15: Paginate user and persondegree list

- config/packages/twig.yaml
- config/services.yaml
- templates/_version.html.twig
- templates/base.html.twig
- templates/base_company.html.twig
- templates/base_degree.html.twig
- templates/base_legislator.html.twig
- templates/base_principal.html.twig
- templates/base_school.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-V342_16: Add copyright and version of app

- src/Controller/Front/FrontSchoolController.php
- src/Controller/PersonDegreeController.php
- src/Controller/Security/UserController.php
- src/Repository/PersonDegreeRepository.php
- templates/persondegree/index.html.twig
- templates/user/index.html.twig
> IFEF-V342_16: Rollback pagination with knp

- config/bundles.php
- config/packages/knp_paginator.yaml
- src/Repository/PersonDegreeRepository.php
> IFEF-V345_15: Disable KnpPaginator bundle

- src/Controller/Security/UserController.php
- src/Repository/PersonDegreeRepository.php
> IFEF-V345_18: Disable knpPaginatorBundle on UserController

- composer.json
- migrations/Version20250126191827.php
- src/Controller/CityController.php
- src/Controller/RegionController.php
- src/Entity/Country.php
- src/Model/FlashBag/FlashBag.php
- src/Repository/CountryRepository.php
- src/Repository/RegionRepository.php
- src/Tools/Utils.php
- templates/city/index.html.twig
- templates/region/index.html.twig
- translations/messages.en.xlf
- translations/messages.es.xlf
- translations/messages.fr.xlf
- translations/messages.pt.xlf
> IFEF-V345_21: Import regions and cities

- composer.json
> IFEF-V345_22: Update phpoffice/phpspreadsheet to a compatible version of php 8.0

- migrations/Version20250210012250.php
- src/Controller/CityController.php
- src/Entity/Country.php
- src/Repository/CountryRepository.php
> IFEF-V345_24: Fix template generation of city

- src/Controller/Front/FrontSchoolController.php
- src/Tools/Utils.php
- templates/GeoLocation/maps.html.twig
- templates/_footer.html.twig
> IFEF-V345-27: Fix PDF export large and remove partenaire button on geolocation page

- templates/GeoLocation/maps.html.twig
- templates/school/content.html.twig
> IFEF-V345_28: Add button "Vos diplômés/Partenaires" only for ROLE_ETABLISSEMENT

- src/Controller/GeoLocationController.php
- src/Entity/School.php
- templates/GeoLocation/maps.html.twig
- templates/_footer.html.twig
> IFEF-V345_29: Fix Format A2 PDF and count of diploma on geolocation

- templates/school/personDegreesEnroll.html.twig
> IFEF-V345_31: Remove extra row on enrollment's template

- src/Controller/Front/FrontSchoolController.php
> IFEF_V345_30: Fix format number of column Phone in enrollment template

- doc/deployment-country.md
> IFEF-V345_32: Add documentation on ./doc/deployment-country.md

- src/Controller/Front/FrontSchoolController.php
- src/Repository/ActivityRepository.php
- src/Repository/SectorAreaRepository.php
> IFEF-V345_33: Fix sector area, activity and diploma translator on enrollment template

- .env.example
- package.json
- src/Repository/SectorAreaRepository.php
> IFEF_V345_35: Add @babel/plugin-proposal-class-properties

- src/Entity/School.php
> IFEF_V345_36: Fix error when create new account

- src/Controller/SchoolController.php
> IFEF_V345_37: Fix bug when edit school (relation with user is remove and user cant connect)

- migrations/Version20250719170538.php
- src/Controller/DashboardController.php
- src/Controller/SchoolController.php
- src/Entity/School.php
- src/Repository/UserRepository.php
> IFEF_V345_38: Fix school leaving user relationship
